##############################################################################
#
#    The MIT License (MIT)
#
#    Copyright (c) 2014 Vivante Corporation
#
#    Permission is hereby granted, free of charge, to any person obtaining a
#    copy of this software and associated documentation files (the "Software"),
#    to deal in the Software without restriction, including without limitation
#    the rights to use, copy, modify, merge, publish, distribute, sublicense,
#    and/or sell copies of the Software, and to permit persons to whom the
#    Software is furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in
#    all copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#    DEALINGS IN THE SOFTWARE.
#
##############################################################################


#############################################################################
# Include common definitions.

include ../makefile.linux.def

################################################################################
# Describe object files.

OBJECTS = $(OBJ_DIR)/galRunTest2.o \
          $(OBJ_DIR)/gutsystem.o

################################################################################
# Supply necessary libraries.

LIBS  += -L $(UNIT_ROOT)/galUtil/$(OBJ_DIR) -l galUtil
LIBS  += -L $(VIVANTE_SDK_LIB) -l GAL
LIBS  += -lm
ifneq ($(QNX), 1)
LIBS  += -ldl -lpthread -lrt
ifeq ($(EGL_API_FB), 0)
ifeq ($(EGL_API_DFB), 1)
INCLUDE += -I$(DFB_DIR)/include
LIBS += -Wl,-rpath $(DFB_DIR)/lib
else
#INCLUDE += -I$(X11_ARM_DIR)/include
#LIBS += -Wl,-rpath $(X11_ARM_DIR)/lib
endif
endif
endif

################################################################################
# Define a shortcut for the main target.
PROGRAM		:= 1
TARGET_NAME  = galRunTest2

################################################################################
# Installation directory.

INSTALL_DIR := $(SDK_DIR)/samples/hal/unit_test

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target

install: extra_install

.PHONY: extra_install
extra_install:
	@-mkdir -p $(INSTALL_DIR)
	@cd $(INSTALL_DIR); find . -name "libgal2D*.so" -exec echo ./$(TARGET_NAME) {} -c ./galTestCommon.cfg \|\| exit \; | sort > runtest.sh
	@chmod +x $(INSTALL_DIR)/runtest.sh
	@-cp -f $(UNIT_ROOT)/config/*.* $(INSTALL_DIR)

